FROM    golang:1.19
WORKDIR /go/src/github.com/alexellis/href-counter/
COPY    app.go .
RUN     go get -d -v golang.org/x/net/html && \
        CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w" -o app .
